function init(self)
	-- Add initialization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed

	if message_id == hash("thunder_been_used") then
		thunder_active = false
		gui.set_scale(gui.get_node("cursor"), vmath.vector3(0.2, 0.2, 1))
		gui.play_flipbook(gui.get_node("cursor"), hash("hand_grab_256"))
	elseif message_id == hash("thunder_not_used") then
		thunder_active = false
		gui.set_scale(gui.get_node("cursor"), vmath.vector3(0.2, 0.2, 1))
		gui.play_flipbook(gui.get_node("cursor"), hash("hand_" .. message["action"] .. "_256"))
	elseif message_id == hash('lightning') then
		gui.set_scale(gui.get_node("cursor"), vmath.vector3(0.85, 0.85, 1))
		gui.play_flipbook(gui.get_node("cursor"), hash("cursor_lightning"))
	end
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
	if action.x and action.y then 
		gui.set_position(gui.get_node("cursor"), vmath.vector3(action.x, action.y, 1))
		if not thunder_active then
			if action.pressed then
				gui.set_scale(gui.get_node("cursor"), vmath.vector3(0.2, 0.2, 1))
				gui.play_flipbook(gui.get_node("cursor"), hash("hand_grab_256"))
			elseif  action.released then
				gui.set_scale(gui.get_node("cursor"), vmath.vector3(0.2, 0.2, 1))
				gui.play_flipbook(gui.get_node("cursor"), hash("hand_open_256"))
			end
		end
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
